# Introduction {#intro}

## Project Updates 

Updates to project - just like a wet lab Lab Book 

### To Do 

### 2020-09-09
+ xCell: Got xCell working in R using MSBB bulk gene expression data. 
  - Was using normalized (library size) gene expression data and adjusted for covariates. Need to use raw counts and adjust for gene length 

### 2020-09-04
+ Initial analysis of haplogroup assocations with ROSMAP pathology data. Some initial positive results between haplogroup K and tau pathology. 

### 2020-09-02
+ Ordinal Logistic Regression 
  - Looking at running OLR for neuropathology outcomes in ROSMAP in particular. Cannot (well you technicaly can) use a linear regression as the assumption of LM will be violated, in particualr the constant marginal effect where the distances between successive points in the dependent variable are assumed to be identical - clearly not the case with a ordinal variable. [Norris, C., et al. 2006](https://dx.doi.org/10.1016/j.jclinepi.2005.09.007)
  - Proportional odds assumption: relationship between each pair of outcome groups is the same, such that the coefficients that describe the relationship between, say, the lowest versus all higher categories of the response variable are the same as those that describe the relationship between the next lowest category and all higher categories, etc.
    * Can check assumption using a LRT or a Wald test (Yee pg 397), also graphically (Harrel; UCLA)
    * Assumption is frequently violated, however, the model can still be powerful and usefull (Harrell pg 313); the practical
implications of violating this assumption are minimal. Assumption is sensetive to other misspeicifcations.
    * Can try using a different link function or introducing interactions; or partial proportional odds
+ References 
  - Abreu, M., Siqueira, A., Caiaffa, W. (2009). Regressão logística ordinal em estudos epidemiológicos. [Revista de Saúde Pública  43(1), 183-194](https://dx.doi.org/10.1590/s0034-89102009000100025)
  - Yee, T. (2015). Vector Generalized Linear and Additive Models, With an Implementation in R. [Springer](https://dx.doi.org/10.1007/978-1-4939-2818-7)
  - Harrell, F. (2015). Regression Modeling Strategies, With Applications to Linear Models, Logistic and Ordinal Regression, and Survival Analysis. [Springer](https://dx.doi.org/10.1007/978-3-319-19425-7)
  - UCLA statiscal consulting: https://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/
- R Packages 
  - VGAM: Conducting OLR using `vlgm`
  - MASS: Conducting OLR using `polyr`
  - Brant: Checks proportional odds assumption when using `polyr` (also aproximate wald test)
  - QMSS: Checks proportional odds assumption when using `vlgm` (LR test)

+ Sample size for logistic regression 
  - Rule of thumb is a minimum sample size for logistic regression of ~10 events per predictor paramater [Riley, R. et al. 2019](https://dx.doi.org/10.1002/sim.7992)
  - However, this is context specific, with the appropiate sample size depending not only on the number of events relative to the number of candidate predictor parameters but also on 1) the total number of participants, 2) the outcome proportion (incidence) in the study population and; 3) the expected predictive performance of the model  
  

### 2020-08-22
+ Initial visulizations of blood cell counts vs mtDNAcn do not show a strong relationship that would indicate a reason for the observed bimodal distribution in the samples with DNA isolated from blood.
+ Maybe due to a batch effect? May be observable if we had date of visit to see if mtDNAcn distribution changes after a given date.

### 2020-08-22

+ Succesfully used bc.bio to call conduct joint calling of AMP-AD + DIAN samples. At a macro haplogroup level, there is little difference in haplogroup assignments. For haplogroups, ~500 samples have a different haplogroup assignment. 
+ Obtained additional ROSMAP datasets including information on [blood cell counts](https://www.radc.rush.edu/docs/var/overview.htm?category=Blood+Measures&subcategory=Routine+laboratory+tests). Plan on evaluting assocation of mtDNAcn with platlets. 
+ mtDNAcn estimates from whole blood DNA can be confounded by cell type heterogeneity, and by the presence of platelets, as platelets do not have nDNA, but have mtDNA, which artificially inflates mtDNAcn. [Han, L. et al 2019](https://dx.doi.org/10.1016/j.psyneuen.2019.04.004)
+ cell counts for samples with available RNA-sequencing data can be deconvoluted using gene expression measured in whole blood. [Yang, S. et al 2020](https://dx.doi.org/10.1101/2020.07.17.209023)
  - Aran, D., Hu, Z., Butte, A. (2017). xCell: digitally portraying the tissue cellular heterogeneity landscape. [Genome Biology  18(1), 220](https://dx.doi.org/10.1186/s13059-017-1349-1)

### 2020-08-07

+ trying to bcbio working 
  - got it working on test set of five samples 
  - used sed to rename chr lables in DIAN
+ Not working on full sample list...

### 2020-08-06

+ SampleIDs for DIAN
  - changed from WGS ID (file name) to sample ID
  - causes issues with fastmitocalc, which uses file name as prefix in output
+ bcbio.variation.recall
  - Does not work when samples are mapped to differen builds. while MT positions are the same, chrm label is different which means the samples on other builds are not recalled.
+ installed [crossmap](https://crossmap.readthedocs.io/en/latest/) using conda install rather than pip
  - crossmap does not work due to chain files using chrM as label, does not lift over correctly
  - solution - use sed to rename all instances of chrM (or MT) to MT. Worked on example file from DIAN. allowed bcbio to work


### 2020-08-05

+ Looking at conducting joint calling using bcbio 
  - Issues with DIAN files, in particular it uses hg38, while AMP-AD uses 37
    * Not sure if this will be an issue, may just be able to use the same reference fasta
    * Tried using [crossmap](https://crossmap.readthedocs.io/en/latest/) to liftover bam files, however mtDNA was unmapped, renames mtDNA as "M" rathern than "MT", also was rather dodgy to get working on minerva, ended up testing it locally 
  - DIAN sampleIDs are different from file names, which must match read groups in bam files for bcbio
+ Redoing sampleIDs for DIAN
  - encounted issue with broken symlinks - took a while to diagnoses and fix 
  - pipeline is working again

## Neuropathological Confirmed AD 
There is consensus to disentangle the clinicopathologic term “Alzheimer’s disease” from AD neuropathologic change. The former refers to clinical signs and symptoms of cognitive and behavioral changes that are typical for patients who have substantial AD neuropathologic change, and is the focus of recent NIA–AA-sponsored consensus reports on three defined stages in a clinical continuum that includes preclinical, mild cognitive impairment, anddementia. The latter refers to the presence and extent of neuropathologic changes of AD observed at autopsy, re-gardless of the clinical setting.

### CERAD Criteria - 1991
Protocol provides neuropathologic definitions of such terms as “definite Alzheimer’s disease’’ (AD), “probable AD,” “possible AD,” and “normal brain” to indicate levels of diagnostic certainty (@Mirra479). The CERAD Neuritic Plaque score forms the basis of later neuropathological difinitions. 

Sections are tacken from: 

- [middle frontal gyrus](https://en.wikipedia.org/wiki/Middle_frontal_gyrus)
- [superior](https://en.wikipedia.org/wiki/Superior_temporal_gyrus) and [middle](https://en.wikipedia.org/wiki/Middle_temporal_gyrus) temporal gyri
- [inferior parietal lobule](https://en.wikipedia.org/wiki/Inferior_parietal_lobule)
- [hippocampus](https://en.wikipedia.org/wiki/Hippocampus) and [entorhinal cortex](https://en.wikipedia.org/wiki/Entorhinal_cortex)
- [midbrain](https://en.wikipedia.org/wiki/Midbrain)

And scored as a semiquantitative measurment: 

- Absent
- Sparese
- Moderate 
- Frequent 

An age-related plaque score is then determined by combining the age of the patient at death and the semiquantitative measure of plaques in the *most severely affected region of the neocortex*. This score is then intergrated with with clinical information the presence or absence of dementia. 

### NIA-Reagan Criteria - 1997

The modified NIA-Reagan diagnosis of Alzheimer’s disease is based on consensus recommendations for postmortem diagnosis of Alzheimer’s disease. The criteria rely on both neurofibrillary tangles (Braak) and neuritic plaques (CERAD). See [NIA Working group consensus 1997](https://doi.org/10.1016/S0197-4580(97)00057-2) and corresponding editorial by [Hyman et al 1997](https://doi.org/10.1097/00005072-199710000-00002). Traditionaly, the criteria require a history of dementia, insofar as they were designed to help address the question of whether AD was the underlying cause of a patient’s dementia.

- CERAD score is a semiquantitative measure of neuritic plaques
  + No neuritic plaques (C0)
  + Sparse/infrequent neuritic plaques (C1)
  + Moderate neuritic plaques (C2)
  + Frequent neuritic plaques (C3)
- Braak Stage is a semiquantitative measure of severity of neurofibrillary tangle (NFT) pathology.
  + no NFTs (B0)
  + stages I/II, with NFTs predominantly in en-torhinal cortex and closely related areas (B1)
  + stages III/IV, withNFTs more abundant in hippocampus and amygdala whileextending slightly into association cortex (B2)
  + stages V/VI,with NFTs widely distributed throughout the neocortex (B3)

| CERAD / Braak | 0 | I/II | III/IV | V/VI |
| ------------- | - | - | - | - |
| None | **Normal** | - | - | - |
| Sparse | - | **Low** | - | - |
| Moderate | - | - |**Intermediate** | - |
| Frequent | - | - | - | **High** |

### NIA-AA Criteria - 2012

The NIA-AA criteria updated and revised the 1997 NIA-Reagan criteria to recognize the pre-clinical stage of AD, enhance the assessment of AD to include amyloid accumulation as well as neurofibrillary change and neuritic plaques. Hyman et al 2012. The criteria relies on an 'ABC' score for AD neuropathologic change that incorporates histopathologic assessments of amyloid β deposits (A - Thal phase), staging of neurofibrillary tangles (B - CERAD), and scoring of neuritic plaques (C - Braak Stage). See [Hyman et al 2012](https://doi.org/10.1016/j.jalz.2011.10.007) for guidlines and [Montine et al 2012](https://doi.org/10.1007/s00401-011-0910-3) for a practial guide.

- Thal Phase is a semiquantitiative measure of the distribution of AB
  + phase 0 or no amyloid
  + phase 1 or isocortical
  + phase 2 or limbic
  + phase 3 or basal ganglia
  + phase 4 or basal forebrain and midbrain
  + phase 5 or pons/medulla oblongata and cerebellum

| Thal | CERAD               | Braak: | None or I/II (B0 or B1) | III/IV (B2) | V/VI (B3) | 
| -    | ----------          | ------ | - | - | - | 
| 0 (A0)   | None (C0)       |        | Other<sup>§</sup> | Other<sup>§</sup>  | Other<sup>§</sup>  |  
| 1/2 (A1)  | None - Sparse (C0 or C1)|        | Low | Low | Low<sup>¶</sup>  | 
|      | Modearte - Frequent C2 or C3) |        | Low<sup>†</sup>  | Intermediate | Intermediate<sup>¶</sup>  | 
| 3 (A2)   | Any C           |        | Low<sup>†</sup>  | Intermediate | Intermediate<sup>¶</sup>  | 
| 4/5 (A3)  | None - Sparse (C0 or C1) |        | Low<sup>†</sup>  | Intermediate | Intermediate<sup>¶</sup>  | 
|      | Modearte - Frequent C2 or C3) |        | Low<sup>†</sup>  | Intermediate | High | 

<sup>§</sup>Medial temporal lobe NFTs in the absence of significant Ab or neuritic plaques occur in older people and may be seen in individuals without cognitiveimpairment, with mild impairment, or with cognitive impairment from causes other than AD. Consider other diseases when clinically or pathologically indicated.

<sup>¶</sup>Widespread NFTs with some Ab/amyloid plaques or limited neuritic plaques are relatively infrequent, and when they occur, other diseases, particularlytauopathies, should be considered. Such cases may not fit easily into a specific Braak stage, which is intended for categorization of AD-type NFTs.

<sup>†</sup>Higher levels of Ab or neuritic plaques with low Braak stage should prompt consideration of contribution by comorbidities such as vascular brain injury,LBD, or HS. Also, consider additional sections as well as repeat or additional protocols to demonstrate other non-AD lesions

For individuals **without cognitive impairmentat** the time tissue was obtained, it is possible that AD neuropathologic change may predate onset ofsymptoms by years. For individuals **with cognitive impairmentat** the time tissue was obtained, “Intermediate” or “High” level (Table 2) of AD neuropathologic change should be considered adequate explanation of cognitive impairment or dementia. When “Low” level of AD neuropathologic change is observed in the setting of cognitive impairment, it is likely that other diseases are present. In all cases with cognitive impairment, regardless of the extent of AD neuropathologicchange, it is essential to determine the presence or absence, as well as extent, of other disease(s) that might have contributed to the clinical deficits. 

Possibility that Thal amyloid stages do not substantially contribute to predicting antemortem cognition compared to CERAD neuritic plaque scores and Braak NFT stages [Serrano-Pozo et al 2016](https://doi.org/10.1093/jnen/nlw026). 
