# snakejob -j 100
# snakejob -j 5000 --notemp --keep-going --until mtDNAcn_mosdepth
# snakejob -j 5000 --until copy --notemp
# snakejob -j 5000 --until mosdepth --notemp
# snakejob -j 5000 --until mity --notemp
# snakejob -j 5000 --until bgzip --notemp
# snakejob -j 5000 --until haplogrep --notemp

workdir: "/sc/arion/projects/LOAD/shea/Projects/mtDNAcn"
