# snakejob -s workflow/MitochondriaPipeline.smk -j 10 --use-conda -np
# snakemake -s workflow/MitochondriaPipeline.smk -j 1 --use-conda -np
# snakemake -s workflow/MitochondriaPipeline.smk --forceall --rulegraph | dot -Tpdf > docs/MitochondriaPipeline.pdf
# snakemake -s workflow/MitochondriaPipeline.smk -j 1 --use-conda --conda-create-envs-only

INPUT: 'data/SampleInfo_test.csv'

outdir: 'sandbox/output'

gatk:
  max_read_length: 151
  coverage_cap: 100000
  max_low_het_sites: 3
  max_reads_per_alignment_start: 75
  m2_extra_args: ""
  m2_extra_filtering_args: ""
  max_alt_allele_count: 4
  vaf_filter_threshold: 0.01
  f_score_beta: 1
  vaf_cutoff: ""

post_process:
  chunk_size: 100
  overwrite: True
  minimum_homref_coverage: 100
  min_het_threshold: 0.10
  min_hom_threshold: 0.95
  min_mito_cn: 50
  max_mito_cn: 500

reference:
  hg38:
    ref_fasta: "raw/reference/hg38/Homo_sapiens_assembly38.fasta"
    ref_dict: "raw/reference/hg38/Homo_sapiens_assembly38.dict"
    ref_fasta_index: "raw/reference/hg38/Homo_sapiens_assembly38.fasta.fai"
  hg19:
    ref_fasta: "raw/reference/hg19/Homo_sapiens_assembly19.fasta"
    ref_dict: "raw/reference/hg19/Homo_sapiens_assembly19.dict"
    ref_fasta_index: "raw/reference/hg19/Homo_sapiens_assembly19.fasta.fai"
  mt:
    mt_dict: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.dict"
    mt_fasta: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta"
    mt_fasta_index: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta.fai"
    mt_amb: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta.amb"
    mt_ann: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta.ann"
    mt_bwt: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta.bwt"
    mt_pac: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta.pac"
    mt_sa: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.fasta.sa"
    non_control_region_interval_list: "raw/reference/chrM/non_control_region.chrM.interval_list"
    blacklisted_sites: "raw/reference/chrM/blacklist_sites.hg38.chrM.bed"
    blacklisted_sites_index: "raw/reference/chrM/blacklist_sites.hg38.chrM.bed.idx"
  mt_shifted:
    mt_shifted_dict: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.dict"
    mt_shifted_fasta: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta"
    mt_shifted_fasta_index: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.fai"
    mt_shifted_amb: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.amb"
    mt_shifted_ann: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.ann"
    mt_shifted_bwt: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.bwt"
    mt_shifted_pac: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.pac"
    mt_shifted_sa: "raw/reference/chrM/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.sa"
    shift_back_chain: "raw/reference/chrM/ShiftBack.chain"
    control_region_shifted_reference_interval_list: "raw/reference/chrM/control_region_shifted.chrM.interval_list"

gnomad_resources:
  ARTIFACT_PRONE_SITES: "raw/gnomad_resources/artifact_prone_sites.bed"
  variant_context: "raw/gnomad_resources/chrM_pos_ref_alt_context_categories.txt"
  phylotree: "raw/gnomad_resources/rCRS-centered_phylo_vars_final_update.txt"
  pon_mt_trna: "raw/gnomad_resources/pon_mt_trna_predictions_08_27_2020.txt"
  mitotip: "raw/gnomad_resources/mitotip_scores_08_27_2020.txt"
  mt_dbsnp154: "raw/gnomad_resources/GCF_000001405.38.chrM.vcf"
